import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "RX Releaf Qualify Front Door",
  description: "Generated by RX Releaf",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const squareScriptSrc =
    process.env.SQUARE_ENVIRONMENT === "production"
      ? "https://web.squarecdn.com/v1/square.js"
      : "https://sandbox.web.squarecdn.com/v1/square.js";

  return (
    <html lang="en">
      <head>
        <Script
          src={squareScriptSrc}
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${poppins.className} font-sans antialiased bg-[#F6F7F2]`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
