import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} font-sans antialiased bg-[#F6F7F2]`}
      >
      <Providers>
        {children}
      </Providers>
      <Script
          src="https://sandbox.web.squarecdn.com/v1/square.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
